[all]
deps=["udhr-ph.md", "README.md", "metric", "distance"]

["README.md"]
deps=["make-readme.js", "phonetic.js"]
exec="node $< >$@"

[metric]
deps=["english.txt", "inglish.txt"]
exec="expr 1000 \* $(diff -w $+ | wc -l) / \( 2 \* $(wc -l <english.txt) \)"

[diff]
deps=["english.txt", "inglish.txt"]
exec="sdiff --width=50 --ignore-all-space $+ || true"

["udhr-ph.md"]
deps=["udhr.md", "convert.js", "phonate.js", "phonetic.js"]
exec="node convert.js <$< >$@"

["phonetic.txt"]
deps=["cmudict-0.7b.txt", "phonemes.sed"]
exec="""
sed -f phonemes.sed <$< >$@ 
"""

["english.txt"]
deps=["cmudict-0.7b.txt"]
exec="""
sed <$< '
/;;;.*$/d
/^[^A-Z]/d
s/.[1-9].//
' | awk '{print $1}' | tr [:upper:] [:lower:] > $@
"""

["inglish.txt"]
deps=["phonetic.txt"]
exec="""
awk <$< '{print $2}' >$@
"""

["cmudict-0.7b"]
exec="wget https://raw.githubusercontent.com/Alexir/CMUdict/master/cmudict-0.7b"

["cmudict-0.7b.txt"]
deps=["cmudict-0.7b"]
exec="sed 's/\r//g' <$< >$@ "

["phonetic.js"]
deps=["phonetic.txt", "make-phonetic.js"]
exec="""
node make-phonetic.js $< >$@
"""

["enwiki-2022-08-29.txt"]
exec="wget https://raw.githubusercontent.com/IlyaSemenov/wikipedia-word-frequency/master/results/enwiki-2022-08-29.txt"

[distance]
deps=["enwiki-2022-08-29.txt", "distance.js", "phonetic.js", "BUILD.toml"]
exec="node distance.js $<"

[clean]
exec="rm -f phonetic.js cmudict-0.7b.txt inglish.txt phonetic.txt udhr-ph.md"